name: Push providers to ECR

on:
  push:
    branches:
      - main 

jobs:
  build_and_push:
    name: Build and push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.CHRIS_SANDBOX_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.CHRIS_SANDBOX_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Login to ECR
        id: ecr-Login
        uses: aws-actions/amazon-ecr-login@v1

      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Build and push
        id: docker-build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: 468948558197.dkr.ecr.us-west-2.amazonaws.com/massdriver/xo:latest
          ssh: |
            default=${{ env.SSH_AUTH_SOCK }}
